[env]
APP_SERVER_HOST = "127.0.0.1"
APP_SERVER_PORT = "3000"
APP_AUTH_SECRET = "1234"
APP_DB_URL = "postgresql://nick:enter@localhost:5432/newsie?connect_timeout=10"
APP_TRACE_STDOUT = "true"
APP_TRACE_FILTER = "trace"
